title: "UVA Public Interest Data Lab"
logo: "assets/img/big-compass-ob.png"
description: "Project site for UVA's Spring 2020 Public Interest Data Lab, a core project of the CommPAS Lab"
theme: "jekyll-theme-minimal"
